### ISSUE TITLE
Custom request handler in httpListener

### ISSUE THREAD

**Issue by aizerin** [marblejs/marble#114]
I'm trying to rewrite part of my express application to marble.js. And I'm not able to implement something like https://expressjs.com/en/api.html#res.sendFile without modification of httpListener itself.

The problem is that I want to use this library for file streaming https://github.com/pillarjs/send. And I need to change default behaviour of requestSubject$.

I think that it can be a useful feature to have option specify custom res.send method instead of default one. And with that it should be possible also specify custom error handler.

If you think that would be useful, I can make some proposal. I have my own httpListener currently.

**Comment by JozefFlakus** [comment]
Can you show me in some short example of how it could look? I mean I would like to see how do you would like to compose it inside Effect `req$` pipeline.

**Comment by aizerin** [comment]
You are right about the custom error, I missed it.

currently, I have it like that.

```js
const serveIndex$ = EffectFactory.matchPath('/')
    .matchType('GET')
    .use(req$ =>
        req$.pipe(
            mapTo({ file: path.join(process.cwd(), 'public', 'index.html') })
        )
    );
```
I just swapped `body` for `file` in stream output.

And my custom http listener has these changes.

```js
requestSubject$
...
mergeMap(out => output$(of(out), res, defaultMetadata)),
                        out$ =>
                            out$.pipe(
                                mergeMap(out => {
                                  if (out.file) {
                                        return fileHandler({
                                            out,
                                            res,
                                            req,
                                        });
                                    }

                                    return of(out).pipe(tap(res.send));
                                })
                            ),
                        catchError(error => 
...
```

and fileHandler is just simple usage of send library. 

```js
const fileHandler = ({ out, res, req }) =>
    of(out).pipe(
        tap(out => {
            const pathname = encodeURI(out.file);
            const file = send(req, pathname);
            file.pipe(res);
        })
   );
```

**Comment by JozefFlakus** [comment]
@aizerin I think you are missing only the ability to pass Node.js streams to **HttpEffectResponse** `body`. I had it previously implemented but for some unknown reason, I forgot about it completely, thus it is not available in Marble.js 2.0... But it is straightforward to add...

Give me some time and I will prepare **v2.1** version with added support for streams. 💪
It should be available tomorrow I hope ;)

**Comment by JozefFlakus** [comment]
@aizerin With version `2.1.0`, which has just been released, you will be able to pass a `ReadableStream` to `HttpEffectResponse` body. With this streaming support, I think there will be no obstacles with integration with `pillarjs/send` library.

Regarding the custom request handlers for Marble.js `httpListener` - I would like to avoid it as far the default handler meets the requirements.

If there will be any other issues, please let me know. I'll reopen this issue.
Big thanks! 💪

**Comment by aizerin** [comment]
Thanks for the new version. Great job with marblejs, looks amazing so far.

**Comment by JozefFlakus** [comment]
@aizerin let me know if you are able to use `pillarjs/send` library by passing it to response `body`.
