### ISSUE TITLE
@marblejs/middleware-logger extend filter options

### ISSUE THREAD

**Issue by SORC3r3r** [marblejs/marble#115]
Is there any way to use the `filter` of the `marblejs/middleware-logger` to filter specific routes?
I have some frequently called routes which I do not want to see in the log.
I know I can just use some `grep` to filter them, but it would be nice to filter it with the `filter` option of the `marblejs/middleware-logger`.

**Comment by JozefFlakus** [comment]
Yup, you can do this easily. 

```typescript
import { logger$ } from '@marblejs/middleware-logger';

const middlewares = [
  logger$({
    filter: req => ... // filter out specific `req.url` paths
  }),
  ...
];

export default httpListener({ middlewares, effects: [] });
```

https://docs.marblejs.com/api-reference-2/middleware-logger#usage

**Comment by knopki** [comment]
@JozefFlakus just to clarify, `logger$`'s filter's signature is `(res: HttpResponse) => boolean;` and `HttpResponse` doesn't have `url` property.

**Comment by JozefFlakus** [comment]
@knopki Hah, you are right. I was confused by the API which I authored 🤦‍♂️.

@SORC3r3r I'll add also support for filtering incoming requests in the upcoming `v2.1` release.

I think that the end API will look like this:
```typescript
logger$({
  filter: (res, req) => ... // you can validate only `req`, only `res` or both
}),
```

**Comment by JozefFlakus** [comment]
Version [2.1.0](https://github.com/marblejs/marble/releases/tag/v2.1.0) has just been released. As described above, you will be able to filter not only by `response` but also by `request`. If there will be something missing I'll reopen this issue.

Thanks! 💪

**Comment by SORC3r3r** [comment]
Awesome, works perfectly fine! 👍
