### ISSUE TITLE
[Question]: How to implement custom middleware?

### ISSUE THREAD

**Issue by cevr** [marblejs/marble#120]
For example, is there a way to implement [a proxy](https://github.com/nodejitsu/node-http-proxy) via middleware?

**Comment by JozefFlakus** [comment]
For more detailed information about building a custom middleware please visit this chapter https://docs.marblejs.com/overview/middlewares#building-your-own-middleware

Example proxy middleware which passes requests to another host and passes the response back to the original caller can look like this:

```typescript
const proxy$: HttpMiddlewareEffect = (req$, res) =>
  req$.pipe(
    mergeMap(passRequestToAnotherHost),
    mergeMap(hostResponse => res.send({
      body: hostResponse.body,
      status: hostResponse.status,
      headers: hostResponse.headers,
    }),
  );
```

`passRequestToAnotherHost` is a function that gets an incoming request as an argument, where the proxy magic is happening (eg. target host calling, custom request/response transformation etc.)

**Comment by cevr** [comment]
@JozefFlakus Thanks for the timely response! This is great. 👍
