### ISSUE TITLE
Add '422 Unprocessable Entity' to HttpStatus enum

### ISSUE THREAD

**Issue by vanyadymousky** [marblejs/marble#121]
First, thanks much for this neat stuff! Being big fan of reactiveness I found myself at home writing these effects and middlewares. 

Can I please ask for adding 422 error code to HttpStatus enum? REST how-tos advise using it when server validation failed. Not suffering much, but would be great to have!

**Comment by JozefFlakus** [comment]
Thanks for kind words!
Sure, will add it in the upcoming `2.1.1` release :)

**Comment by JozefFlakus** [comment]
Version 2.1.1 is released. It includes the extended `HttpStatus` enum.
You can read the full changelog [here](https://docs.marblejs.com/other/changelog#2-1-1-2019-04-10).
