### ISSUE TITLE
Support compression  

### ISSUE THREAD

**Issue by Jerry-Hong** [marblejs/marble#122]
Hello 
I really love marblejs!! I want to use it on my project and also contribute it if I can. 
BTW is there a talk channel for marblejs? like [spectrum](https://spectrum.chat/), [gitter](https://gitter.im/), [discord](https://discordapp.com/)

---

I wanna compress response(gzip) like [express-compression](https://github.com/expressjs/compression).
Middleware looks like only update `req` but not `res`

```javascript
// effects.combiner.ts
export const combineMiddlewares = <T, U>
  (...effects: Effect<T, T, U>[]) =>
  (input$: Observable<T>, client: U, meta: EffectMetadata): Observable<T> =>
    effects.reduce((i$, effect) => effect(i$, client, meta!), input$);
```

So user can not add compress feature by add a compression middleware.

**Comment by JozefFlakus** [comment]
Thanks for kind words!
There is already a [Gitter](https://gitter.im/marblejs) channel for Marble.js but looks like nobody wants to talk ¯\_(ツ)_/¯

For response compression, you can make use of [output$](https://docs.marblejs.com/advanced/output) interceptor where you can attach a compression logic, which for example can be piped to the response.

This is only a dummy idea of how it can be implemented:
```typescript
const output$: HttpOutputEffect = res$ =>
  res$.pipe(
    // lets assume that res.body is a ReadableStream
    // and 'accept-encoding' is set to 'gzip'
    map(res =>  ({
      ...res,
      headers: { ...res.headers, 'Content-Encoding': 'gzip' },
      body: res.body.pipe(zlib.createGzip()),
    }),
  );
```

**Comment by Jerry-Hong** [comment]
@JozefFlakus 
I look into `output$` source code. The `res$` is just an observable of plain object from user defined effect$ right?
I think `res$` is a little confuse with res from nodejs `http` module. And also user can not really customize res from http?

**Comment by JozefFlakus** [comment]
Hymm... right. I will try to include the initial request somewhere. Will try to add this in the upcoming `2.1.1` release.

**Comment by JozefFlakus** [comment]
The idea for this improvement will look like this:

```typescript
const output$: HttpOutputEffect = (res$, _, { initiator }) =>
  res$.pipe(
    // lets assume that res.body is a ReadableStream
    // and 'initiator.headers.accept-encoding' is set to 'gzip'
    map(res =>  ({
      ...res,
      headers: { ...res.headers, 'Content-Encoding': 'gzip' },
      body: res.body.pipe(zlib.createGzip()),
    }),
  );
```

So in general, `output$` effect will have an ability to get an initiator which will contain a contextual object (eg. `HttpRequest`), so the developer will be able to grab all relevant information when needed from Effect metadata. The same pattern is used inside `ErrorEffect` where you can grab from meta object the occurred `error`.

**Comment by JozefFlakus** [comment]
Version 2.1.1 is released. It includes the extended `EffectMetadata` object from which you can grab the initial request. You can read the full changelog [here](https://docs.marblejs.com/other/changelog#2-1-1-2019-04-10).
