### ISSUE TITLE
Query parameter ending on '.com' returns download/error

### ISSUE THREAD

**Issue by SORC3r3r** [marblejs/marble#145]
**Describe the bug**
I am using marblejs in one of my applications and encountered a weird behaviour if I send a query looking like this `GET 127.0.0.1:1337?userId=test@test.com`.
Turns out that it breaks because of the `.com` at the end of the query.
I would like to consume a JSON file there, but somehow it is always interpreted with an `application/x-msdownload` header and results my application to return a 500 HTTP error.
I used your "hello world" example to reproduce it.

**To Reproduce**
Setup the "hello world" example.
Do a request like this `GET 127.0.0.1:1337?userId=test@test.com`.
Receive a download file called `download.exe`

**Expected behavior**
Do not interpret the request as a download request.

**Desktop (please complete the following information):**
 - OS: macOS Mojave Version 10.14.4
 - marblejs@2.2.2
 - Node version 8.15.10

**Comment by JozefFlakus** [comment]
Thanks for spotting this bug! Fixed in [v2.2.3](https://github.com/marblejs/marble/releases/tag/v2.2.3)

**Comment by SORC3r3r** [comment]
Nice! Thanks for the quick fix!
