### ISSUE TITLE
Error when used requestValidator$

### ISSUE THREAD

**Issue by jvaca92** [marblejs/marble#159]
**Describe the bug**
When using validators with module @marblejs/middleware-io and then call the REST service I have recieved server internal error. The error message is below.

{
"error":{
"status": 500,
"message": "testing_1.isTestingMetadataOn is not a function"
}

**To Reproduce**

Error when use validator
```
import { HttpEffect, use, HttpError, HttpStatus } from '@marblejs/core';
import { map,  mergeMap, catchError } from 'rxjs/operators';
import { requestValidator$, t } from '@marblejs/middleware-io';
import { of, throwError } from 'rxjs';
import { getCustomRepository } from 'typeorm';
import { UserRepository } from '@api/user/dao/user.repository';

const emailValidator$ = requestValidator$({
  body: t.type({
    email: t.string
  })
});

export const findUserByEmailEffect$: HttpEffect = req$ =>
  req$.pipe(  
    use(emailValidator$),
    mergeMap(req => of(req.body.email).pipe(
      mergeMap(getCustomRepository(UserRepository).findUserByEmail),
      map(user => ({body: user}),
      catchError(() => throwError(
        new HttpError("Could not found user", HttpStatus.NOT_FOUND)
      ))
      )
    ))
  )
```

Without validator everything work fine but the body is uknown which is not also useful.

```
import { HttpEffect, HttpError, HttpStatus } from '@marblejs/core';
import { map,  mergeMap, catchError } from 'rxjs/operators';
// import { requestValidator$, t } from '@marblejs/middleware-io';
import { of, throwError } from 'rxjs';
// import { getCustomRepository } from 'typeorm';
// import { UserRepository } from '@api/user/dao/user.repository';

// const emailValidator$ = requestValidator$({
//   body: t.type({
//     email: t.string
//   })
// });

export const findUserByEmailEffect$: HttpEffect = req$ =>
  req$.pipe(  
    // use(emailValidator$),
    mergeMap(req => of(req.body).pipe(
      // mergeMap(getCustomRepository(UserRepository).findUserByEmail),
      map(user => ({body: user}),
      catchError(() => throwError(
        new HttpError("Could not found user", HttpStatus.NOT_FOUND)
      ))
      )
    ))
  )
```

**Expected behavior**
I would expect to be able get value from the database when the validator successfully validate the request body.

**Desktop (please complete the following information):**
 - OS - Windows 10
 - Package + Version: @marblejs/middleware-io + latest
 - Node version: v10.15.3

**Comment by krzysztof-miemiec** [comment]
Can you specify which package versions do you use?

**Comment by JozefFlakus** [comment]
Looks like you don't have aligned package versions. @marblejs ecosystem requires from you to have aligned versioning. So, in general, it is recommended to have to use the same versioning for dependent packages as you have for the `@marblejs/core`. Eg. when the `@marblejs/core` uses `"^2.1"` then all other officials `@marblejs/*` modules should have the same `"^2.1"` versioning.

**Comment by jvaca92** [comment]
You right. my package json was with these versions which was the problem. After changed to 2.1.0 everything works perfect.

Thanks fro help a thumbs up for this framework

Wrong package json
```
@marblejs/core": "2.1.0",
    "@marblejs/middleware-body": "2.1.0",
    "@marblejs/middleware-cors": "^2.1.0",
    "@marblejs/middleware-io": "^2.3.1",
    "@marblejs/middleware-jwt": "2.1.0",
    "@marblejs/middleware-logger": "2.1.0",
```

Correct package json
```
@marblejs/core": "2.1.0",
    "@marblejs/middleware-body": "2.1.0",
    "@marblejs/middleware-cors": "^2.1.0",
    "@marblejs/middleware-io": "2.1.1",
    "@marblejs/middleware-jwt": "2.1.0",
    "@marblejs/middleware-logger": "2.1.0",
```

**Comment by JozefFlakus** [comment]
I would suggest also to lock the `@marblejs/middleware-cors` to `2.1.0` or set all packages to `^2.3.1`. `@marblejs` uses semantic versioning - there are no breaking changes in minor releases so you can do it without any fear :)

**Comment by jvaca92** [comment]
Fixed it. Thanks for additional help :).
