### ISSUE TITLE
Any way to subscript broken connection event?

### ISSUE THREAD

**Issue by skyuplam** [marblejs/marble#160]
Hi there,

Is there any way to known when a websocket client's connection is broken so that I can do a follow-up action, e.g. update the database about the client's status.

**Comment by JozefFlakus** [comment]
Hi!

Can you describe how the WebSocket server is bootstrapped? Do you use an intermediate HTTP server and upgrade the connection or the WebSocket server directly? Based on that I can help you better.

Right now the `@marblejs/websockets` module doesn't have "cool" direct access to connected client events, but it will change in the next major release. Right now I can propose you a temporary way of solving this problem :)

**Comment by skyuplam** [comment]
Hi Józef,

Yes, I use an intermediate HTTP server and upgrade the connection or the
WebSocket server directly.

**Comment by JozefFlakus** [comment]
Ok, so the temporary solution consists of reacting to `listening` server event:

```typescript
const handleWsServerConnectionEvents = (wsServer: MarbleWebSocketServer) => {
  wsServer.on('connection', conn => {
    // do whatever you want... eg:
    conn.send('hello!');
  });
};

const listening$: HttpServerEffect = (event$, _, { ask }) =>
  event$.pipe(
    matchEvent(ServerEvent.listening),
    map(event => event.payload),
    tap(({ port, host }) => {

      ask(WsServerToken)
        .map(handleWsServerConnectionEvents)
        .getOrElseL(() => { throw new Error('WsServerToken not bound to context'); });

      console.log(`Server running @ http://${host}:${port}/ 🚀`);
    }),
  );
```

**Comment by JozefFlakus** [comment]
Version [3.1 released](https://github.com/marblejs/marble/releases/tag/v3.1.0).
