### ISSUE TITLE
Send a HTTP request

### ISSUE THREAD

**Issue by GavanWilhite** [marblejs/marble#174]
Forgive me if I've missed this somewhere, but is it possible to send, rather than receive, a http request with marble?

**Comment by JozefFlakus** [comment]
So far `@marblejs/core` doesn't have included HttpClient. You can use easily any library that supports promises/observables, eg. [axios](https://github.com/axios/axios).

**Comment by krzysztof-miemiec** [comment]
If you need to create custom http clients with error handling and authorization (without wrapping up axios/request libs in some kind of abstraction), I can recommend `@coolio/http` package (I'm the author of the package 😉).

**Comment by GavanWilhite** [comment]
Thanks folks!
