### ISSUE TITLE
Server close event never gets called

### ISSUE THREAD

**Issue by randomnerd** [marblejs/marble#175]
Hi there!
I believe there is a bug createServer factory:
```javascript
event$(serverEventSubject.pipe(takeWhile(e => !isCloseEvent(e))), server, metadata).subscribe();
```
takeWhile takes a second argument, `inclusive` - setting it to `true` should allow server close callback to get called.
```javascript
event$(serverEventSubject.pipe(takeWhile(e => !isCloseEvent(e), true)), server, metadata).subscribe();
```
thanks!

**Comment by JozefFlakus** [comment]
Fixed in version `v3.0.0-rc.2`
