### ISSUE TITLE
uuid imports need to be fixed for compatibility with latest version

### ISSUE THREAD

**Issue by jollytoad** [marblejs/marble#241]
Default import of uuid was deprecated in uuid@3, it's now been removed in latest uuid@7.

Example:

https://github.com/marblejs/marble/blob/master/packages/core/src/context/context.token.factory.ts

```
import * as uuid from 'uuid';
```

should be replaced with:

```
import { v4 as uuid } from 'uuid';
```

(This is backwards compatible and will work with both uuid@3 and uuid@7)

For more details: https://github.com/uuidjs/uuid#upgrading-from-uuid3

**Comment by JozefFlakus** [comment]
Thanks for spotting it! I'm open for pull requests :)

**Comment by jollytoad** [comment]
I was considering it - is the 3.x branch on master?

**Comment by JozefFlakus** [comment]
Yes 🙂
