### ISSUE TITLE
middleware-io requestValidator$ incompatible with io-ts codecs

### ISSUE THREAD

**Issue by tstelzer** [marblejs/marble#256]
Using the latest version of core and middleware-io, defining a codec directly via `io-ts` and using it in `requestValidator$` leads to a failed build due to seemingly incompatible type guards. Bumping the io-ts dependency seems to resolve the issue. [A PR has been created.
](https://github.com/marblejs/marble/pull/255)

**To Reproduce**
Check out https://github.com/tstelzer/marble-playground with minimal code to reproduce the issue.

**Comment by JozefFlakus** [comment]
Fixed in version [3.1.1](https://github.com/marblejs/marble/releases/tag/v3.1.1)
