### ISSUE TITLE
Request matchPath('*')

### ISSUE THREAD

**Issue by nairihar** [marblejs/marble#27]
I think it will be good if user can receive request using '*' symbol.
As I noticed you use "path-to-regexp" library, If it's good feature and you want to have this I can help you, just I need to know should I use "path-to-regexp" or something other?

Thanks

**Comment by JozefFlakus** [comment]
Can you post here some code samples for use cases?
Right now if _Effect_ doesn't compose `matchPath` operator it behaves like `matchPath('*')` - it handles all requests in his group. In my opinion adding custom matcher like this can be redundant and will obfuscate the `matchPath` logic. But if there are some other use cases that we are not aware of we can think about this idea.

**Comment by nairihar** [comment]
In Marble If we want to handle routes which has 404 status (not found that path) how we can do that ?
As I understood from source code we can't.

Also we can add some "not handled error" Observable where user can subscribe and do some work for that error.

**Comment by couzic** [comment]
This thread makes me think. Currently, middlewares handle incoming requests, would it make sense to have a second group of middlewares that handle outgoing responses ? Or instead of incoming/outgoing, it could be beforeEffects/afterEffects.
It would provide easy solutions for cases like handling all 404 responses.

**Comment by JozefFlakus** [comment]
@couzic but why would we need a second layer for processing outgoing requests? The end of the request lifecycle should be visible inside Effect pipeline which is then processed by the `responseHandler`. If there would be some need for applying some transformations for sent data then you can simply use `use` operator for composing it just before final `map`.

But definitely the custom `error.handlers` should have an ability to intercept `404` responses in case when no Effect will match the request.

**Comment by JozefFlakus** [comment]
@nairihar `*` matching added in version `0.4.0`. You can see the latest changelog here: [marblejs.gitbook.io/marble/changelog1](https://marblejs.gitbook.io/marble/changelog#0-4-0-2018-05-31)

**Comment by JozefFlakus** [comment]
@nairihar [here](https://github.com/marblejs/marble/blob/master/example/src/controllers/api.controller.ts#L15) you can find an example implementation for `404` route detection.

In the next days I will update the [marblejs.com](http://marblejs.com) with detailed description how routing is resolved (introduced in #40).

**Comment by couzic** [comment]
@JozefFlakus I agree with you, it was just a naive thought. The * solution works for me !
