### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED] when using rxjs v7

### ISSUE THREAD

**Issue by brielov** [marblejs/marble#324]
**Describe the bug**
It seems that rxjs version 7 breaks something inside marble.

**To Reproduce**
```
yarn add @marblejs/core fp-ts rxjs
```
Run the example as shown on the website

**Desktop (please complete the following information):**
 - MacOS 11.3
 - Node 16.0

The following error is thrown: 

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/scheduler/AsyncScheduler' is not defined by "exports" in 'node_modules/rxjs/package.json'

**Comment by JozefFlakus** [comment]
In order to have a compatibility with latest RxJS release we have to bump the framework to the next major version - `4.0`. Please confirm my thoughts.

**Comment by brielov** [comment]
I don't know how much RxJS has changed under the hood. If I'm not mistaken, they have renamed some operators which may cause current marble applications to break. So, I think I agree with you on bumping marble's version to `4.0`.

**Comment by FredericEspiau** [comment]
RxJs a changed a lot between 6 and 7 so yeah, it would require a major version

**Comment by JozefFlakus** [comment]
In progress 🙃 https://github.com/marblejs/marble/discussions/330#discussioncomment-872200

**Comment by JozefFlakus** [comment]
Closing because `RxJS v7` support is added in the `v4.0` release candidate.
