### ISSUE TITLE
Use middleware on GroupedEffects created with combineRoutes()

### ISSUE THREAD

**Issue by couzic** [marblejs/marble#36]
In my development environment, I'm adding CORS headers to my API responses. But my API endpoints are combined :
`combineRoutes('/api', effects)`

I would like a way to use my CORS middleware on all API effects, without having to call `use()` on each of them. I was thinking of something similar to `httpListener`'s signature :
`combineRoutes('/api', { middlewares, effects })`

**Comment by JozefFlakus** [comment]
Definately - that something that we have in mind and defined for future releases. So your request validated my thoughts 👍 

But I'm thinking about the following API:

```
combineRoutes(
  path: string,
  effects: Effect[],
  middlewares: Effect<HttpRequest>[],
```

In order to not introduce breaking changes. But I'm open for discussion 😄

**Comment by couzic** [comment]
No strong opinions here, whatever works for you.

**Comment by JozefFlakus** [comment]
@couzic version `0.5.0` has been released. See latest changelog. Also you can check PR #47 for more details. Cheers! 💪

BTW. Updated [documentation](marblejs.com) for new changes is on the way.
