### ISSUE TITLE
HttpErrorEffect stop the server and result with "Cannot read property 'response' of undefined"

### ISSUE THREAD

**Issue by carere** [marblejs/marble#384]
First of all, thx for this awesome package, i was looking for a small web framework (smaller than nest 😅), and i found yours !!

**Describe the bug**
As the title said, when i use error effect when configuring the server, it result with an error in case of an route not found.
```
[
  @marblejs/core error:

  🚨  An unexpected error "Cannot read property 'response' of undefined" occured while sending a response. Please check your output/error effect.
  
  ] {
  name: 'CoreError'
}
```

**To Reproduce**
All you need to do is to call http://127.0.0.1:1337/foo with the following script
```js
import { createServer, httpListener, HttpStatus, r } from "@marblejs/http";
import { logger$ } from "@marblejs/middleware-logger";
import { map, mapTo } from "rxjs";
import { bodyParser$ } from "@marblejs/middleware-body";

const api$ = r.pipe(
  r.matchPath("/"),
  r.matchType("GET"),
  r.useEffect((req$) => req$.pipe(mapTo({ body: "Hello, world!" })))
);

const error$ = (req$) =>
  req$.pipe(
    map((_) => {
      return {
        status: HttpStatus.BAD_REQUEST,
        body: "Even when i don't use the error param, it's not working ",
      };
    })
  );

const server = createServer({
  port: 1337,
  hostname: "127.0.0.1",
  listener: httpListener({
    middlewares: [logger$(), bodyParser$()],
    effects: [api$],
    error$,
  }),
});

const main = async () => await (await server)();
main();

```

**Expected behavior**
I think it should work as expected when using specific error effect 😄 

**Desktop (please complete the following information):**
 - Elementary OS 6 Odin (Built on Ubuntu 20.04.3 LTS) & Linux 5.11.0-40-generic
 - Node (v16.13.0) & Yarn (v1.22.17)
 - Package.json:
 ```json
    "@marblejs/core": "4.*",
    "@marblejs/http": "4.*",
    "@marblejs/middleware-body": "4.*",
    "@marblejs/middleware-logger": "4.*",
    "fp-ts": "2.*",
    "rxjs": "7.*"
```

**Additional context**
I using MarbeJS with ReScript 😄 . Since, i'm a big lover of RxJS, i would like to promote your framework in rescript community !!

**Comment by JozefFlakus** [comment]
With the latest version `v4` the interface for `HttpErrorEffect` changed:
```typescript
Observable<{ error, request }>
  -> Observable<{ status, body, headers, request }>
```
You didn't get the error because you didn't assert `error$` to `HttpErrorEffect` type interface:
which means:
```typescript
const error$: HttpErrorEffect = req$ =>
  req$.pipe(
    map(({ request }) => {
      return {
        request,
        status: HttpStatus.BAD_REQUEST,
        body: "Even when i don't use the error param, it's not working ",
      };
    })
  );
```

**Comment by carere** [comment]
Ok thx for the answer, i understand now 😉
