### ISSUE TITLE
Typescript typing error, HttpRequest do not match with http.IncomingMessage on`http.createServer()`

### ISSUE THREAD

**Issue by nolanrigo** [marblejs/marble#43]
Hello 👋 a big thanks for this library, RxJS as http server is really awesome 😍 

**Describe the bug**

I got a typing issue with `@marblejs/core` on my typescript project,
I created a listener (`httpListener()`) and created a http server (`http.createServer(app)`) but got a typing error :

```
Argument of type '(req: HttpRequest, res: HttpResponse) => void' is not assignable to parameter of type '((request: IncomingMessage, response: ServerResponse) => void) | undefined'.
  Type '(req: HttpRequest, res: HttpResponse) => void' is not assignable to type '(request: IncomingMessage, response: ServerResponse) => void'.
    Types of parameters 'req' and 'request' are incompatible.
      Type 'IncomingMessage' is not assignable to type 'HttpRequest'.
        Property 'matchPath' is missing in type 'IncomingMessage'.

createServer(app).listen(
```

This error is thrown only when `strictFunctionTypes` is activated on my compiler config

```
{
  "compilerOptions": {
    "strictFunctionTypes": true
  }
}
```

**To Reproduce**

I create a branch on my project to reproduce the issue (https://github.com/zap4you/server/tree/marblejs-issue)

```sh
$ git clone git@github.com:zap4you/server.git marblejs-issue
$ cd marblejs-issue
$ git checkout marbejs-issue
$ npm i
$ npm run build
```

**Expected behavior**
I'm not sure but the function that `httpListener` returns should be more strictly typed to match with `http.createServer` expectation ?!.

**Desktop (please complete the following information):**

```
 - macOs 10.13.4
 - node@9.11.1 / npm@6.1.0
 - typescript@2.9.11
 - @marblejs/core@0.4.0
 - @types/node@10.1.2
```

**Comment by JozefFlakus** [comment]
Hi, thanks for kind words!

It turned out that our *example* project structure hid this error  by not properly typed `app` parameter. 🙈

```
const createServer = app => {
  ...
};
```

I've created a PR #44 with solution to this problem. The fix will be available in version `0.4.1`. I'll let you know when it will be ready.

Cheers!

**Comment by nolanrigo** [comment]
Thanks for the fast fix 💪. I let you close this issue when is needed.

**Comment by JozefFlakus** [comment]
@nolanrigo version `0.4.1` is released. You can check a changelog [here](https://marblejs.gitbook.io/marble/changelog#0-4-1-2018-06-03)  💪
