### ISSUE TITLE
@marblejs/core is missing chalk dependency

### ISSUE THREAD

**Issue by goulderb** [marblejs/marble#77]
**Describe the bug**
The @marblejs/core package utilizes chalk in the error/error.factory.js file. This is not listed as a required dependency, which causes the installed dependencies to be incorrect when this is installed in production mode (npm i --production). This causes any marblejs application to crash since the package cannot be imported.

**To Reproduce**
Create a boilerplate server with @marblejs/core and install dependencies via npm i --production with no pre-existing node_modules.

**Expected behavior**
I expect the chalk dependency to be added to the @marblejs/core package.

**Desktop (please complete the following information):**
 - OS: Mac OS X High Sierra
 - Package + Version: @marblejs/core v1.2.0
 - Node version: v10.13.0

**Comment by JozefFlakus** [comment]
Thanks for detecting this issue! Fixed in version `v1.2.1` 💪
