### ISSUE TITLE
Gitbook Docs middleware-logger typo

### ISSUE THREAD

**Issue by jsonberry** [marblejs/marble#82]
Visit https://marblejs.gitbook.io/marble/available-middlewares/logger#usage

Missing `$` from the const assignments in both examples

## Examples
Expected
```javascript
export const logger$ = loggerWithOpts$(); 
```

Actual
```javascript
export const logger$ = loggerWithOpts(); // add missing $ from loggerWithOpts
```

**Comment by JozefFlakus** [comment]
Fixed. Thanks @jsonberry 💪
